### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by pepijndevos** [glhr/dash-university-rankings#1]
Please add a license file to clarify the rights users of this software have ;-)

**Comment by prabowobagas** [comment]
Thank you

**Comment by glhr** [comment]
需要更多的卡尔曼滤波器

**Comment by prabowobagas** [comment]
我不说话电晕

**Comment by pepijndevos** [comment]
鸭点派

On February 17, 2020 10:29:05 PM GMT+01:00, glhr <notifications@github.com> wrote:
>需要更多的卡尔曼滤波器>
>>
>-- >
>You are receiving this because you authored the thread.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/glhr/dash-university-rankings/issues/1#issuecomment-587164881

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
